### YamlMime:Role 
title: Solutions Architect (Architecte de Solutions) 
metadata: 
  title: Solutions Architect (Architecte de Solutions)
  description: Les Solutions Architects (architectes de solutions) Microsoft doivent posséder une expertise en informatique, réseau, stockage et sécurité. 
uid: role.solution-architect
summary: | 
  Les Solutions Architects (architectes de solutions) Microsoft doivent posséder une expertise en informatique, réseau, stockage et sécurité.
subTitle: Les Solutions Architects (architectes de solutions) Microsoft doivent posséder une expertise en informatique, réseau, stockage et sécurité.
certificationPaths: 
- title: Azure Solutions Architect
  linkedInKeywords: Azure Solutions Architect
  uid: certification-path.azure-solutions-architect 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-solutions-architect
    levels:
    - advanced    
- title: Dynamics 365 Finance and Operations Apps Solution Architect
  linkedInKeywords: Dynamics 365 Finance and Operations Apps Solution Architect
  uid: certification-path.d365-finance-and-operations-apps-solution-architect-expert
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate  
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate 
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate 
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate 
  - uid: certification.d365-finance-and-operations-apps-solution-architect-expert
    levels:
    - advanced  
- title: Dynamics 365 + Power Platform Solution Architect
  linkedInKeywords: Dynamics 365 + Power Platform Solution Architect
  uid: certification-path.power-apps-and-d365-solution-architect-expert
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate
  - uid: certification.power-apps-and-d365-solution-architect-expert
    levels:
    - advanced
- title: Power Platform Solution Architect
  linkedInKeywords: Power Platform Solution Architect
  uid: certification-path.power-platform-solution-architect-expert
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.power-platform-functional-consultant-associate
    levels:
    - intermediate
  - uid: certification.power-platform-developer-associate
    levels:
    - intermediate
  - uid: certification.power-platform-solution-architect-expert
    levels:
    - advanced
certifications:
- uid: certification.azure-solutions-architect
  requiredExams:
  - uid: exam.az-303
  - uid: exam.az-304
- uid: certification.d365-finance-and-operations-apps-solution-architect-expert
  requiredExams:
  - uid: exam.mb-700
- uid: certification.azure-for-sap-workloads-specialty
  requiredExams:
  - uid: exam.az-120
- uid: certification.power-platform-solution-architect-expert
  requiredExams:
  - uid: exam.pl-600
resources:
- title: Guide de formation et de certification Microsoft
  description: Découvrez toutes les certifications dans un guide de formation et de certification concis.
  href: https://aka.ms/TrainingCertDeck
- title: Affiche de formation et de certification
  description: Choisissez la voie de la réussite avec cette affiche de formation et de certification.
  href: https://aka.ms/traincertposter
- title: Aide à la certification
  href: ../help.md
  description: Obtenez de l’aide à travers nos Forums de support de Microsoft Certification. Un modérateur du forum répondra sous 24 heures (du lundi au vendredi).
